import Vue from 'vue'
import {
	Button,
	Form,
	FormItem,
	Input,
	Steps,
	Upload,
	Checkbox,
	CheckboxGroup,
	Step,
	Tabs,
	TabPane,
	Cascader,
	Alert,
	Option,
	Select,
	Table,
	Tree,
	Tag,
	TableColumn,
	Dialog,
	Pagination,
	Switch,
	Tooltip,
	Message,
	Card,
	Col,
	Row,
	Container,
	Header,
	Aside,
	Main,
	Submenu,
	Menu,
	MenuItemGroup,
	MenuItem,
	Breadcrumb,
	BreadcrumbItem,
	Footer,
	MessageBox,
	Radio,
	RadioButton,
	ButtonGroup,
	RadioGroup,
	TimePicker,
	DatePicker,
	Backtop,
	Image,
	Avatar,
	Carousel,
	CarouselItem,
	Link,
	Divider,
	Autocomplete
} from 'element-ui'
Vue.use(Divider)
Vue.use(Autocomplete)
Vue.use(Link)
Vue.use(CarouselItem)
Vue.use(Carousel)
Vue.use(Avatar)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Button)
Vue.use(Input)
Vue.use(Header)
Vue.use(Container)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Submenu)
Vue.use(Menu)
Vue.use(MenuItemGroup)
Vue.use(MenuItem)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Card)
Vue.use(Row)
Vue.use(Col)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Switch)
Vue.use(Pagination)
Vue.use(Tooltip)
Vue.use(Dialog)
Vue.use(Tag)
Vue.use(Tree)
Vue.use(Select)
Vue.use(Option)
Vue.use(Cascader)
Vue.use(Alert)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Steps)
Vue.use(Step)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(Upload)
Vue.use(Footer)
Vue.use(Radio)
Vue.use(RadioButton)
Vue.use(ButtonGroup)
Vue.use(RadioGroup)
Vue.use(TimePicker)
Vue.use(DatePicker)
Vue.use(Backtop)
Vue.use(Image)
// 将Message以$message为名挂载到全局Vue的方法上，这样所有vm实例都可以使用这个方法
Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm
